name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: echo "BASE_URL=/creature-pixel/" >> $GITHUB_ENV

      - name: Build the project
        env:
          NODE_ENV: production
        run: npm run generate

      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        run: npx gh-pages --dotfiles -d .output/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
